Repository palantir/palantir-cloudpak, pull requests merged in 2021-03, with the labels that each got.

#25 Update palantir-cloudpak image tag to latest
  cpd/modules/palantir-operator/x86_64/1.0.0/main.yaml
Labels: merge when ready

#27 Update palantir-operator image version to 0.5.1
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: merge when ready

#35 Add configuration options for data storage encryption and access
  README.md
  cpd/modules/palantir-operator/x86_64/1.0.0/install-override.yaml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator-configmap.yaml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: no changelog

#36 Improve instructions for data access and encryption
  README.md
Labels: no changelog

#38 Update validation steps
  README.md
Labels: merge when ready, no changelog

#39 Update install-override.yaml
  cpd/modules/palantir-operator/x86_64/1.0.0/install-override.yaml
Labels: merge when ready, no changelog

#41 1.0.0 Release
  changelog/@unreleased/pr-41.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator-configmap.yaml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: merge when ready

#42 Remove bash scripts
  changelog/@unreleased/pr-42.v2.yml
  cpd/install-prereqs.sh
  cpd/run.sh
Labels: autorelease, merge when ready

#43 State requirements on Watson Studio and Watson ML
  README.md
Labels: no changelog

#44 fix: Upgrade palantir operator to 1.0.1
  changelog/@unreleased/pr-44.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: merge when ready

#45 fix: Upgrade operator to 1.0.3
  changelog/@unreleased/pr-45.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/install-override.yaml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator-configmap.yaml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: autorelease, merge when ready

#47 Revert "Add environment variables for logging"
  changelog/@unreleased/pr-46.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: merge when ready

#48 Add InsecureSkipVerify annotation to pod template
  changelog/@unreleased/pr-48.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: merge when ready

#40 Start collecting health from the palantir operator
  changelog/@unreleased/pr-40.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: do not merge

#49 Upgrade operator to 1.2.0
  changelog/@unreleased/pr-49.v2.yml
  cpd/modules/palantir-operator/x86_64/1.0.0/palantir-operator.yaml
Labels: merge when ready

#50 Use IBM_ENTITLEMENT_KEY instead of ICR_KEY
  cpd/cpd-cli/repo.yaml
Labels: no changelog
